dubbo:
  application: # 应用配置
    name: user
    module: simple-user
    version: 1.0.0
    environment: dev
  registries: # 注册中心
    nacos:
      protocol: nacos
      timeout: 10s
      address: 127.0.0.1:8848
  config-center:
    protocol: nacos               # 配置中心协议 nacos / apollo / zookeeper / etcd
    address: "127.0.0.1:8848"     # 配置中心地址
    namespace: "public"           # 命名空间（nacos 有用）
    group: "dubbo"                # 配置组
    data-id: "dubbogo.yaml"         # 配置文件 dataId（nacos 用）
  protocols: # 协议配置
    tripleProtocol:
      name: tri
      port: 20000
  provider: # 服务提供者配置
    services:
      UserProvider:
        interface: lingmou.simple.user.api.UserService # proto文件中定义的服务名称
  logger: # 日志配置
    level: "info"
    appender: "file" 
    file:
      name: "runtime/logs/dubbo.log" # 暂时不知道怎么取环境变量
      maxSize: 100 # 100MB
      maxBackups: 3 # 保留 3 个文件
      maxAge: 300 # 300天
      compress: true # 压缩
